// Generated by scripts/build-official-player-compat.js. Edit official_player_compat_src instead.
(function () {
  function compatLog(message) {
    if (typeof window.logLine === "function") window.logLine(message);
    else if (window.console && console.log) console.log(message);
  }

  function getJsonpCallbackName(url) {
    var match = String(url).match(/[?&](?:jsonCallBack|callback|cb)=([^&]+)/);
    return match ? decodeURIComponent(match[1]) : "";
  }

  var DEV_INVENTORY_KEY_PREFIX = "officialProxyDevFreeUnlockInventory:v2:";
  var DEV_FLOWER_AMOUNT = 9999;
  var DEV_FLOWER_COIN_AMOUNT = DEV_FLOWER_AMOUNT * 100;

  function parseUrlParams(url) {
    var params = {};
    var query = String(url || "").split("?")[1] || "";
    query = query.split("#")[0];
    query.split("&").forEach(function (part) {
      if (!part) return;
      var pair = part.split("=");
      var key = decodeURIComponent(pair.shift() || "");
      var value = decodeURIComponent(pair.join("=") || "");
      if (!key) return;
      params[key] = value;
    });
    return params;
  }

  function intParam(params, keys, fallback) {
    for (var index = 0; index < keys.length; index++) {
      var value = params[keys[index]];
      if (value !== undefined && value !== "") {
        var parsed = parseInt(value, 10);
        if (!isNaN(parsed)) return parsed;
      }
    }
    return fallback;
  }

  function getDevInventoryKey() {
    return DEV_INVENTORY_KEY_PREFIX + String(window.__officialProxyGameId || "default");
  }

  var compatPatches = [];
  var compatGameProfiles = [];

  function registerCompatPatch(name, order, installer) {
    compatPatches.push({ name: name, order: order, installer: installer });
  }

  function registerGameProfile(profile) {
    compatGameProfiles.push(profile);
  }

  function gameProfileMatches(profile) {
    if (String(window.__officialProxyGuid || "") !== String(profile.guid || "")) return false;
    if (profile.versions === "*") return true;
    var currentVersion = String(window.__officialProxyVersion || "");
    return (profile.versions || []).some(function (version) {
      return String(version) === currentVersion;
    });
  }

  function getActiveGameProfiles() {
    return compatGameProfiles.filter(gameProfileMatches);
  }

  function getActiveCompatCapabilities() {
    var capabilities = [];
    getActiveGameProfiles().forEach(function (profile) {
      (profile.capabilities || []).forEach(function (capability) {
        if (capabilities.indexOf(capability) === -1) capabilities.push(capability);
      });
    });
    return capabilities;
  }

  function hasCompatCapability(capability) {
    return getActiveCompatCapabilities().indexOf(capability) !== -1;
  }

  function installRegisteredCompatPatches() {
    var ok = false;
    compatPatches.slice().sort(function (left, right) {
      return left.order - right.order;
    }).forEach(function (patch) {
      try {
        ok = patch.installer() || ok;
      } catch (error) {
        compatLog("official proxy " + patch.name + " patch skipped: " +
          (error && (error.stack || error.message) || error));
      }
    });
    return ok;
  }

  registerGameProfile({
    id: "66rpg-1569947-legacy-v2",
    guid: "0a235c54f16c431ab5736c92997edb47",
    versions: "*",
    capabilities: ["padded-dbutton", "extended-dsystem"]
  });

  registerGameProfile({
    id: "66rpg-1683317-v1544",
    guid: "468fe16ef100b2f24215e6874783ad66",
    versions: ["1544"],
    capabilities: ["extended-dsystem", "native-v108-sized-cui", "jump-story-v2063"]
  });

  registerGameProfile({
    id: "66rpg-1692665-v56",
    guid: "9076a69f88f6c963ec508dabe224a73e",
    versions: ["56"],
    capabilities: ["extended-dsystem", "native-v108-sized-cui", "jump-story-v2063"]
  });

  window.__officialProxyCompatRegistry = {
    activeProfileIds: function () {
      return getActiveGameProfiles().map(function (profile) { return profile.id; });
    },
    activeCapabilities: getActiveCompatCapabilities,
    hasCapability: hasCompatCapability
  };

  var cuiCompatibilityInstalled = false;

  function showBuiltinNameEditor(event, argv) {
    var gameData = window.GloableData && GloableData.getInstance && GloableData.getInstance();
    var strings = gameData && gameData.dGameSystem && gameData.dGameSystem.dGameString;
    if (!strings || typeof strings.setVar !== "function") return false;

    var rawFields = String(argv && argv[3] || "").split(",");
    var declaredCount = parseInt(argv && argv[4], 10);
    var fieldCount = !isNaN(declaredCount) && declaredCount > 0 ? declaredCount : Math.floor(rawFields.length / 3);
    var fields = [];
    for (var index = 0; index < fieldCount; index++) {
      var offset = index * 3;
      var variableIndex = parseInt(rawFields[offset + 2], 10);
      if (isNaN(variableIndex)) continue;
      fields.push({
        label: String(rawFields[offset] || "名称"),
        variableIndex: variableIndex
      });
    }
    if (!fields.length) return false;

    var existing = document.getElementById("official-proxy-name-editor");
    if (existing) existing.remove();

    var overlay = document.createElement("div");
    overlay.id = "official-proxy-name-editor";
    overlay.style.cssText = "position:fixed;inset:0;z-index:2147483647;display:flex;align-items:center;justify-content:center;padding:24px;background:rgba(24,20,22,.58);font-family:'Microsoft YaHei',sans-serif;box-sizing:border-box";

    var form = document.createElement("form");
    form.style.cssText = "width:min(520px,92vw);max-height:90vh;overflow:auto;padding:24px 26px;border:1px solid rgba(255,255,255,.75);border-radius:18px;background:rgba(255,252,248,.98);box-shadow:0 18px 50px rgba(45,26,34,.28);box-sizing:border-box";

    var title = document.createElement("h2");
    title.textContent = "填写角色名称";
    title.style.cssText = "margin:0;color:#4d383f;text-align:center;font-size:24px;font-weight:700";
    form.appendChild(title);

    var hint = document.createElement("p");
    hint.textContent = "这些名称会用于后续剧情，请填写后继续。";
    hint.style.cssText = "margin:8px 0 20px;color:#8a717a;text-align:center;font-size:14px";
    form.appendChild(hint);

    var inputs = [];
    fields.forEach(function (field, fieldIndex) {
      var row = document.createElement("label");
      row.style.cssText = "display:block;margin-top:13px;color:#624b54;font-size:14px;font-weight:600";
      row.textContent = field.label === "自定义" ? "自定义名称 " + (fieldIndex + 1) : field.label;

      var input = document.createElement("input");
      input.type = "text";
      input.required = true;
      input.maxLength = 20;
      input.autocomplete = "off";
      input.placeholder = "请输入" + row.textContent;
      try {
        var currentValue = typeof strings.getVar === "function" ? strings.getVar(field.variableIndex) : "";
        input.value = currentValue == null ? "" : String(currentValue);
      } catch (error) {}
      input.style.cssText = "display:block;width:100%;height:42px;margin-top:6px;padding:0 12px;border:1px solid #decbd2;border-radius:10px;outline:none;background:#fff;color:#4e3b42;font-size:16px;box-sizing:border-box";
      input.addEventListener("focus", function () { input.style.borderColor = "#e85f8e"; });
      input.addEventListener("blur", function () { input.style.borderColor = "#decbd2"; });
      row.appendChild(input);
      form.appendChild(row);
      inputs.push({ input: input, variableIndex: field.variableIndex });
    });

    var validation = document.createElement("p");
    validation.style.cssText = "display:none;margin:12px 0 0;color:#d94c71;text-align:center;font-size:13px";
    validation.textContent = "请填写全部名称。";
    form.appendChild(validation);

    var submit = document.createElement("button");
    submit.type = "submit";
    submit.textContent = "确认并继续";
    submit.style.cssText = "display:block;width:100%;height:44px;margin-top:20px;border:0;border-radius:11px;background:#e94d80;color:#fff;font-size:16px;font-weight:700;cursor:pointer";
    form.appendChild(submit);

    ["mousedown", "mouseup", "click", "touchstart", "touchend", "keydown"].forEach(function (eventName) {
      overlay.addEventListener(eventName, function (domEvent) { domEvent.stopPropagation(); });
    });

    form.addEventListener("submit", function (domEvent) {
      domEvent.preventDefault();
      domEvent.stopPropagation();
      var values = inputs.map(function (item) { return item.input.value.trim(); });
      if (values.some(function (value) { return !value; })) {
        validation.style.display = "block";
        return;
      }
      inputs.forEach(function (item, inputIndex) {
        strings.setVar(item.variableIndex, values[inputIndex]);
      });
      overlay.remove();
      var ui = window.UIManager && UIManager.getInstance && UIManager.getInstance();
      if (ui) {
        ui.isSCUIShow = false;
        if (ui.gameSystemUILayer && typeof ui.gameSystemUILayer.setMenuVisible === "function") {
          ui.gameSystemUILayer.setMenuVisible(true);
        }
      }
      if (gameData) gameData.CUIFromIndex = -1;
      event.isSuiFinish = true;
      event.finish();
    });

    overlay.appendChild(form);
    document.body.appendChild(overlay);
    var ui = window.UIManager && UIManager.getInstance && UIManager.getInstance();
    if (ui) {
      ui.isSCUIShow = true;
      if (ui.gameSystemUILayer && typeof ui.gameSystemUILayer.setMenuVisible === "function") {
        ui.gameSystemUILayer.setMenuVisible(false);
      }
    }
    if (gameData) gameData.CUIFromIndex = 10014;
    window.setTimeout(function () { if (inputs[0]) inputs[0].input.focus(); }, 0);
    compatLog("official proxy built-in name editor opened fields=" + fields.length);
    return true;
  }

  function installCuiCompatibilityPatch() {
    if (
      cuiCompatibilityInstalled ||
      !window.org_event ||
      !org_event.CallMenuEvent ||
      !org_event.CallMenuEvent.prototype ||
      typeof org_event.CallMenuEvent.prototype.init !== "function"
    ) return false;

    var originalCallMenuInit = org_event.CallMenuEvent.prototype.init;
    org_event.CallMenuEvent.prototype.init = function () {
      var argv = this.data && this.data.Argv;
      if (parseInt(argv && argv[0], 10) === 10014 && showBuiltinNameEditor(this, argv)) {
        this.index = 10014;
        return;
      }
      return originalCallMenuInit.apply(this, arguments);
    };
    org_event.CallMenuEvent.prototype.init.__officialProxyCuiCompatibilityWrapped = true;
    cuiCompatibilityInstalled = true;
    compatLog("official proxy built-in CUI compatibility enabled");
    return true;
  }

  registerCompatPatch("built-in CUI", 30, installCuiCompatibilityPatch);

  function readDevInventory() {
    try {
      var raw = window.localStorage && localStorage.getItem(getDevInventoryKey());
      var parsed = raw ? JSON.parse(raw) : {};
      return parsed && typeof parsed === "object" ? parsed : {};
    } catch (error) {
      return {};
    }
  }

  function writeDevInventory(inventory) {
    try {
      if (window.localStorage) localStorage.setItem(getDevInventoryKey(), JSON.stringify(inventory));
    } catch (error) {}
  }

  function devInventoryArray() {
    var inventory = readDevInventory();
    return Object.keys(inventory).map(function (key) {
      return { goods_id: parseInt(key, 10), using_num: parseInt(inventory[key], 10) || 0 };
    }).filter(function (item) {
      return item.goods_id > 0;
    });
  }

  function addDevInventory(goodsId, buyNum) {
    if (!goodsId || goodsId <= 0) return null;
    var inventory = readDevInventory();
    var key = String(goodsId);
    var next = (parseInt(inventory[key], 10) || 0) + Math.max(1, buyNum || 1);
    inventory[key] = next;
    writeDevInventory(inventory);
    return { goods_id: goodsId, using_num: next };
  }

  function getDevInventoryItem(goodsId) {
    if (!goodsId || goodsId <= 0) return null;
    var inventory = readDevInventory();
    var key = String(goodsId);
    var usingNum = parseInt(inventory[key], 10) || 0;
    return usingNum > 0 ? { goods_id: goodsId, using_num: usingNum } : null;
  }

  function mergeObject(target, source) {
    target = target && typeof target === "object" ? target : {};
    for (var key in source) {
      if (Object.prototype.hasOwnProperty.call(source, key)) target[key] = source[key];
    }
    return target;
  }

  function devFlowerState() {
    return {
      fresh_flower_num: DEV_FLOWER_AMOUNT,
      wild_flower_num: 0,
      wild_flower: 0,
      tanhua_flower_num: DEV_FLOWER_AMOUNT,
      tanHuaPlayFowerStr: DEV_FLOWER_AMOUNT,
      flower_num: DEV_FLOWER_AMOUNT,
      num: DEV_FLOWER_AMOUNT,
      sum: DEV_FLOWER_AMOUNT,
      payFlowerNumStr: String(DEV_FLOWER_AMOUNT)
    };
  }

  function devUserFlowerAccount() {
    return {
      coin1: { coin_count: DEV_FLOWER_COIN_AMOUNT },
      coin2: { coin_count: DEV_FLOWER_COIN_AMOUNT },
      coin_count: DEV_FLOWER_COIN_AMOUNT,
      gold_count: DEV_FLOWER_COIN_AMOUNT,
      flower_count: DEV_FLOWER_AMOUNT,
      fresh_flower_num: DEV_FLOWER_AMOUNT,
      wild_flower_num: 0,
      tanhua_flower_num: DEV_FLOWER_AMOUNT,
      num: DEV_FLOWER_AMOUNT,
      sum: DEV_FLOWER_AMOUNT
    };
  }

  function devAwardPayload() {
    return {
      is_receive: 0,
      is_received: 0,
      received: 0,
      can_receive: 1,
      can_get: 1,
      status: 1,
      flower_num: DEV_FLOWER_AMOUNT,
      need_flower: 0,
      award_flower: DEV_FLOWER_AMOUNT,
      coin_count: DEV_FLOWER_COIN_AMOUNT,
      data: devFlowerState()
    };
  }

  function applyDevFlowerState() {
    if (!window.__officialProxyDevFreeUnlock) return false;

    if (window.commonPlayer) {
      commonPlayer.loginStatus = true;
      commonPlayer.flower = mergeObject(commonPlayer.flower, devFlowerState());
      commonPlayer.flower_unlock = 0;
      commonPlayer.sendFlower = commonPlayer.sendFlower || {};
      commonPlayer.sendFlower.userCoin = mergeObject(commonPlayer.sendFlower.userCoin, devUserFlowerAccount());
      commonPlayer.sendFlower.sendFlowerState = function (callback) {
        applyDevFlowerState();
        if (typeof callback === "function") callback(true);
      };
      commonPlayer.sendFlower.up_Sent_Flower = function (num, callback) {
        applyDevFlowerState();
        if (typeof callback === "function") callback(true);
      };
    }

    if (window.GloableData && GloableData.getInstance) {
      var data = GloableData.getInstance();
      data.isFreeLimit = false;
      data.isFreeTime = 0;
      data.flowerUnlock = 0;
      data.gameFvTimes = 999999;
      data.flowerHua = DEV_FLOWER_AMOUNT;
      data.flowerMallHua = DEV_FLOWER_AMOUNT;
    }

    if (window.OrgWeb && OrgWeb.prototype && !OrgWeb.prototype.__officialProxyDevFlowerPatched) {
      OrgWeb.prototype.__officialProxyDevFlowerPatched = true;
      OrgWeb.prototype.getFlowrHuaNum = function () { return DEV_FLOWER_AMOUNT; };
      OrgWeb.prototype.getHaveFlower = function () { return DEV_FLOWER_COIN_AMOUNT; };
      OrgWeb.prototype.getReWidFlower = function () { return DEV_FLOWER_AMOUNT; };
      OrgWeb.prototype.getWebUserFlower = function (thisArg, callback) {
        applyDevFlowerState();
        if (typeof callback === "function") callback.call(thisArg, DEV_FLOWER_AMOUNT);
      };
      OrgWeb.prototype.getAllFlower = function (callback) {
        applyDevFlowerState();
        if (typeof callback === "function") callback();
      };
      OrgWeb.prototype.updateUserInfoCoin = function (callback) {
        applyDevFlowerState();
        if (typeof callback === "function") callback();
      };
      OrgWeb.prototype.sendReWidFlower = function (callback) {
        applyDevFlowerState();
        if (typeof callback === "function") callback();
      };
      OrgWeb.prototype.initSendFlower = function (thisArg, callback, priceType) {
        applyDevFlowerState();
        if (typeof callback === "function") callback.call(thisArg, true, priceType);
      };
      OrgWeb.prototype.sendFlower = function (thisArg, callback, num) {
        applyDevFlowerState();
        if (typeof callback === "function") callback.call(thisArg, [num || 1, true]);
      };
    }

    return true;
  }

  function applyLocalSaveUserFlags(target) {
    if (!target || typeof target !== "object") return false;
    var changed = false;
    function setValue(key, value) {
      if (target[key] !== value) {
        target[key] = value;
        changed = true;
      }
    }
    setValue("savePageShowLocal", 1);
    setValue("showLocalLoadM", 1);
    if (target.curOPCloudOption === undefined || target.curOPCloudOption === null) {
      target.curOPCloudOption = 0;
      changed = true;
    }
    return changed;
  }

  function applyCommonPlayerLocalSaveFlags() {
    if (!window.commonPlayer) return false;
    commonPlayer.userInfos = commonPlayer.userInfos || {};
    return applyLocalSaveUserFlags(commonPlayer.userInfos);
  }

  function installLocalSaveModePatch() {
    var patched = applyCommonPlayerLocalSaveFlags();

    if (typeof window.SAL_getUserData === "function" && !window.SAL_getUserData.__officialProxyLocalSaveWrapped) {
      var originalGetUserData = window.SAL_getUserData;
      window.SAL_getUserData = function () {
        var userData = originalGetUserData.apply(this, arguments) || {};
        applyLocalSaveUserFlags(userData);
        if (userData.userData) applyLocalSaveUserFlags(userData.userData);
        if (userData.userInfos) applyLocalSaveUserFlags(userData.userInfos);
        return userData;
      };
      window.SAL_getUserData.__officialProxyLocalSaveWrapped = true;
      patched = true;
      compatLog("official proxy local save user-data patch enabled");
    }

    if (patched) compatLog("official proxy local save flags enabled");
    return patched;
  }

  var cloudSavePayloadInstalled = false;

  var saveFileLocalModeInstalled = false;

  function installSaveFileLocalModePatch() {
    if (
      saveFileLocalModeInstalled ||
      !window.view ||
      !view.SaveFileUI ||
      !view.SaveFileUI.prototype
    ) return false;

    var proto = view.SaveFileUI.prototype;
    var patched = false;

    function selectLocalMode(saveView, updateState) {
      try {
        var gd = window.GloableData && GloableData.getInstance ? GloableData.getInstance() : null;
        if (gd) {
          gd.isCloud = false;
          gd.isOpenSaveFileUI = true;
        }
        if (window.utils && utils.addCookie && window.GloableStaticData && saveView) {
          if (saveView.saveSelectkey) {
            utils.addCookie(saveView.saveSelectkey, GloableStaticData.SELECT_SAVE_TYPE_LOCAL);
          }
          if (saveView.saveGuidekey) utils.addCookie(saveView.saveGuidekey, "1");
          if (saveView.firstOpenKey) utils.addCookie(saveView.firstOpenKey, "1");
        }
        if (saveView) {
          try {
            if (saveView.saveGuidekey) localStorage.setItem(saveView.saveGuidekey, "1");
            if (saveView.firstOpenKey) localStorage.setItem(saveView.firstOpenKey, "1");
          } catch (storageError) {}
          if (updateState && typeof saveView.changeState === "function") saveView.changeState(0);
        }
        if (window.UIManager && UIManager.getInstance && window.view && view.SaveFileGuideMediator) {
          UIManager.getInstance().closeView(view.SaveFileGuideMediator.NAME, false);
        }
      } catch (error) {
        compatLog("official proxy local save UI selection failed: " + (error && (error.stack || error.message) || error));
      }
    }

    if (typeof proto.drawCloudBtn === "function" && !proto.drawCloudBtn.__officialProxyLocalModeWrapped) {
      var originalDrawCloudBtn = proto.drawCloudBtn;
      proto.drawCloudBtn = function () {
        selectLocalMode(this, false);
        var result = originalDrawCloudBtn.apply(this, arguments);
        selectLocalMode(this, true);
        return result;
      };
      proto.drawCloudBtn.__officialProxyLocalModeWrapped = true;
      patched = true;
    }

    if (typeof proto.clickCloud === "function" && !proto.clickCloud.__officialProxyLocalModeWrapped) {
      proto.clickCloud = function () {
        selectLocalMode(this, false);
        if (typeof this.clickLocal === "function") return this.clickLocal();
      };
      proto.clickCloud.__officialProxyLocalModeWrapped = true;
      patched = true;
    }

    if (!patched) return false;
    proto.__officialProxyLocalModePatched = true;
    saveFileLocalModeInstalled = true;
    compatLog("official proxy save UI forced to local mode");
    return true;
  }

  function installCloudSavePayloadPatch() {
    if (
      cloudSavePayloadInstalled ||
      !window.view ||
      !view.SaveFileUI ||
      !view.SaveFileUI.prototype ||
      typeof view.SaveFileUI.prototype.downComplete !== "function"
    ) return false;

    var originalDownComplete = view.SaveFileUI.prototype.downComplete;
    view.SaveFileUI.prototype.downComplete = function (response) {
      if (response && response.data && typeof response.data !== "string") {
        var normalized = {};
        for (var key in response) {
          if (Object.prototype.hasOwnProperty.call(response, key)) normalized[key] = response[key];
        }
        normalized.data = JSON.stringify(response.data);
        response = normalized;
      }
      return originalDownComplete.call(this, response);
    };
    view.SaveFileUI.prototype.downComplete.__officialProxyPayloadWrapped = true;
    cloudSavePayloadInstalled = true;
    compatLog("official proxy cloud save payload normalization enabled");
    return true;
  }

  registerCompatPatch("local save mode", 70, installLocalSaveModePatch);
  registerCompatPatch("save UI local mode", 80, installSaveFileLocalModePatch);
  registerCompatPatch("cloud save payload", 90, installCloudSavePayloadPatch);

  function getDevFreeUnlockPayload(url) {
    var text = String(url || "");
    var lower = text.toLowerCase();
    var params = parseUrlParams(text);
    var goodsId = intParam(params, ["goods_id", "goodsId", "goodsid", "item_id", "itemId", "id"], 0);
    var buyNum = intParam(params, ["buy_num", "buyNum", "buynum", "num", "count"], 1);
    var isLocalApi =
      lower.indexOf("propshop/") !== -1 ||
      lower.indexOf("/engine/") !== -1 ||
      lower.indexOf("/game/") !== -1 ||
      lower.indexOf("/task/") !== -1 ||
      lower.indexOf("/pay") !== -1 ||
      lower.indexOf("/flower") !== -1 ||
      lower.indexOf("/account") !== -1 ||
      lower.indexOf("/user/") !== -1 ||
      lower.indexOf("/ajax/") !== -1 ||
      lower.indexOf("ajax/") !== -1 ||
      lower.indexOf("/api/client") !== -1;

    if (!isLocalApi) return null;

    if (lower.indexOf("game_flower_by_me") !== -1) {
      return { status: 1, msg: "local platform flower state", data: devFlowerState() };
    }
    if (lower.indexOf("get_flower") !== -1) {
      return { status: 1, msg: "local platform flower account", data: devUserFlowerAccount() };
    }
    if (
      lower.indexOf("contains/flower") !== -1 ||
      lower.indexOf("share_game") !== -1 ||
      lower.indexOf("pay/flower") !== -1
    ) {
      applyDevFlowerState();
      return { status: 1, msg: "local platform flower ok", data: devFlowerState() };
    }
    if (lower.indexOf("all_share_award_conf") !== -1 || lower.indexOf("share_award_conf") !== -1) {
      return { status: 1, msg: "local platform award ok", data: devAwardPayload() };
    }
    if (lower.indexOf("getmyaccountmoney") !== -1 || lower.indexOf("accountmoney") !== -1 || lower.indexOf("balance") !== -1) {
      return {
        status: 1,
        data: {
          coin_count: DEV_FLOWER_COIN_AMOUNT,
          gold_count: DEV_FLOWER_COIN_AMOUNT,
          flower_count: DEV_FLOWER_AMOUNT,
          diamond_count: DEV_FLOWER_AMOUNT,
          acoin: DEV_FLOWER_AMOUNT
        }
      };
    }
    if (lower.indexOf("getuserhaveallpropnum") !== -1) {
      return { status: 1, data: devInventoryArray() };
    }
    if (lower.indexOf("getuserhavepropnum") !== -1 || lower.indexOf("propnum") !== -1) {
      var item = goodsId ? getDevInventoryItem(goodsId) : null;
      return { status: 1, data: goodsId ? (item ? [item] : []) : devInventoryArray() };
    }
    if (lower.indexOf("get_user_hp") !== -1 || lower.indexOf("init_user_hp") !== -1) {
      return { status: 1, data: { hp: 999999, max_hp: 999999 } };
    }
    if (lower.indexOf("getlimitfreetime") !== -1 || lower.indexOf("getoldlimitfreetime") !== -1) {
      return { status: 1, data: { is_free: 1, time: 0 } };
    }
    if (
      lower.indexOf("createbuyorder") !== -1 ||
      lower.indexOf("unlock") !== -1 ||
      lower.indexOf("buy") !== -1 ||
      lower.indexOf("pay") !== -1 ||
      lower.indexOf("consume") !== -1 ||
      lower.indexOf("charge") !== -1 ||
      lower.indexOf("flower") !== -1
    ) {
      var boughtItem = goodsId ? addDevInventory(goodsId, buyNum) : null;
      return {
        status: 1,
        msg: "local platform unlock",
        data: {
          ok: 1,
          success: 1,
          is_buy: 1,
          is_unlock: 1,
          unlock: 1,
          goods_id: boughtItem ? boughtItem.goods_id : goodsId,
          buy_num: buyNum,
          using_num: boughtItem ? boughtItem.using_num : buyNum,
          order_id: "local-platform-unlock"
        }
      };
    }
    return null;
  }

  function getLocalPlatformApiPayload(url) {
    var payload = getDevFreeUnlockPayload(url);
    if (payload) return payload;

    var lower = String(url || "").toLowerCase();
    if (lower.indexOf("new_get_game_ad_list") !== -1) {
      return {
        status: 1,
        msg: "local platform ad list",
        data: {
          ad: {
            adurl: "",
            imgurl: "",
            mobile_img_url: ""
          }
        }
      };
    }
    if (lower.indexOf("get_game_info") !== -1) {
      return {
        status: 1,
        msg: "local platform game info",
        data: {
          game: {
            first_pub_time: "2026-01-01",
            author_uname: "",
            gname: "",
            month_card: 0
          }
        }
      };
    }
    if (lower.indexOf("get_limit_free_status") !== -1 || lower.indexOf("getlimitfreetime") !== -1) {
      return { status: 1, msg: "local platform free status", data: { status: 0, is_free: 1, time: 0 } };
    }
    if (lower.indexOf("get_orange_flower_color_status") !== -1) {
      return { status: 1, msg: "local platform orange flower status", data: { status: 0 } };
    }
    if (lower.indexOf("check_refund_flower") !== -1) {
      return { status: 1, msg: "local platform refund status", data: { status: 0, have_refund: 0 } };
    }
    if (lower.indexOf("get_status_v3") !== -1) {
      return { status: 1, msg: "local platform light text status", data: { status: 0 } };
    }
    if (lower.indexOf("get_global_cfg") !== -1) {
      return { status: 1, msg: "local platform prop shop config", data: {} };
    }
    if (lower.indexOf("get_goods_list") !== -1) {
      return { status: 1, msg: "local platform prop shop goods", data: [] };
    }
    if (lower.indexOf("cloud_load_ex") !== -1 || lower.indexOf("cloud_save_ex") !== -1) {
      return { status: 1, msg: "ok", data: null };
    }
    if (lower.indexOf("oweb_log.php") !== -1) {
      return { ret: 1 };
    }
    return null;
  }

  function createResolvedAjaxResult(payload) {
    var result = {
      abort: function () {},
      done: function (handler) {
        if (typeof handler === "function") setTimeout(function () { handler(payload, "success", result); }, 0);
        return result;
      },
      fail: function () { return result; },
      always: function (handler) {
        if (typeof handler === "function") setTimeout(function () { handler(result, "success"); }, 0);
        return result;
      },
      status: 200,
      responseJSON: payload,
      responseText: JSON.stringify(payload)
    };
    return result;
  }

  function installLocalRequestPatch() {
    var patched = false;
    if (typeof window.SAL_request === "function" && !window.SAL_request.__officialProxyLocalRequestWrapped) {
      var originalRequest = window.SAL_request;
      window.SAL_request = function (url, method, dataType, callback) {
        var payload = getLocalPlatformApiPayload(url);
        if (payload) {
          compatLog("official proxy local API SAL_request " + url);
          if (typeof callback === "function") setTimeout(function () { callback(200, payload); }, 0);
          return null;
        }
        return originalRequest.apply(this, arguments);
      };
      window.SAL_request.__officialProxyLocalRequestWrapped = true;
      patched = true;
    }

    if (window.$ && $.ajax && !$.ajax.__officialProxyLocalRequestWrapped) {
      var originalAjax = $.ajax;
      $.ajax = function (options) {
        var url = typeof options === "string" ? options : options && options.url;
        var payload = getLocalPlatformApiPayload(url);
        if (payload) {
          compatLog("official proxy local API ajax " + url);
          var result = createResolvedAjaxResult(payload);
          setTimeout(function () {
            if (options && typeof options.success === "function") options.success(payload, "success", result);
            if (options && typeof options.complete === "function") options.complete(result, "success");
          }, 0);
          return result;
        }
        return originalAjax.apply(this, arguments);
      };
      $.ajax.__officialProxyLocalRequestWrapped = true;
      patched = true;
    }

    if (patched) compatLog("official proxy local API patch enabled");
    return patched;
  }

  function isLocalNetworkNoiseToast(value) {
    var text = String(value || "");
    return text.indexOf("网络异常") !== -1 &&
      (text.indexOf("退出重进") !== -1 || text.indexOf("联系客服") !== -1 || text.indexOf("刷新重试") !== -1);
  }

  function hideLocalNetworkNoiseObject(object) {
    if (!object) return object;
    object.__officialProxyHiddenNetworkNoiseToast = true;
    try { object.visible = false; } catch (error) {}
    try { object._visible = false; } catch (error) {}
    try { object._opacity = 0; } catch (error) {}
    try {
      if (typeof object.setVisible === "function") object.setVisible(false);
    } catch (error) {}
    try {
      if (typeof object.setOpacity === "function") object.setOpacity(0);
    } catch (error) {}
    return object;
  }

  function installNetworkNoiseToastFilterPatch() {
    var state = window.__officialProxyNetworkNoiseToastFilter ||
      (window.__officialProxyNetworkNoiseToastFilter = { lastEmptySprite: null, logged: false });
    var patched = false;

    if (typeof window.SALSprite === "function" && !window.SALSprite.__officialProxyNetworkNoiseWrapped) {
      var originalSprite = window.SALSprite;
      window.SALSprite = function (path) {
        var object = originalSprite.apply(this, arguments);
        if (!path) state.lastEmptySprite = { object: object, at: Date.now() };
        return object;
      };
      window.SALSprite.__officialProxyNetworkNoiseWrapped = true;
      patched = true;
    }

    if (typeof window.SALText === "function" && !window.SALText.__officialProxyNetworkNoiseWrapped) {
      var originalText = window.SALText;
      window.SALText = function (text) {
        var args = Array.prototype.slice.call(arguments);
        var isNoise = isLocalNetworkNoiseToast(text);
        if (isNoise) {
          args[0] = "";
          var last = state.lastEmptySprite;
          if (last && Date.now() - last.at < 1000) hideLocalNetworkNoiseObject(last.object);
        }
        var object = originalText.apply(this, args);
        if (isNoise) {
          hideLocalNetworkNoiseObject(object);
          if (!state.logged) {
            state.logged = true;
            compatLog("official proxy suppressed local network toast");
          }
        }
        return object;
      };
      window.SALText.__officialProxyNetworkNoiseWrapped = true;
      patched = true;
    }

    if (typeof window.SAL_addElement === "function" && !window.SAL_addElement.__officialProxyNetworkNoiseWrapped) {
      var originalAddElement = window.SAL_addElement;
      window.SAL_addElement = function (parent, child) {
        if (child && child.__officialProxyHiddenNetworkNoiseToast) hideLocalNetworkNoiseObject(child);
        var result = originalAddElement.apply(this, arguments);
        if (child && child.__officialProxyHiddenNetworkNoiseToast) hideLocalNetworkNoiseObject(child);
        return result;
      };
      window.SAL_addElement.__officialProxyNetworkNoiseWrapped = true;
      patched = true;
    }

    if (typeof window.SAL_setElementOpacity === "function" && !window.SAL_setElementOpacity.__officialProxyNetworkNoiseWrapped) {
      var originalSetOpacity = window.SAL_setElementOpacity;
      window.SAL_setElementOpacity = function (object, opacity) {
        if (object && object.__officialProxyHiddenNetworkNoiseToast) {
          var args = Array.prototype.slice.call(arguments);
          args[1] = 0;
          return originalSetOpacity.apply(this, args);
        }
        return originalSetOpacity.apply(this, arguments);
      };
      window.SAL_setElementOpacity.__officialProxyNetworkNoiseWrapped = true;
      patched = true;
    }

    if (typeof window.SAL_setElementVisible === "function" && !window.SAL_setElementVisible.__officialProxyNetworkNoiseWrapped) {
      var originalSetVisible = window.SAL_setElementVisible;
      window.SAL_setElementVisible = function (object, visible) {
        if (object && object.__officialProxyHiddenNetworkNoiseToast) {
          var args = Array.prototype.slice.call(arguments);
          args[1] = false;
          return originalSetVisible.apply(this, args);
        }
        return originalSetVisible.apply(this, arguments);
      };
      window.SAL_setElementVisible.__officialProxyNetworkNoiseWrapped = true;
      patched = true;
    }

    if (typeof window.SAL_runAction === "function" && !window.SAL_runAction.__officialProxyNetworkNoiseWrapped) {
      var originalRunAction = window.SAL_runAction;
      window.SAL_runAction = function (object, action, callback) {
        if (object && object.__officialProxyHiddenNetworkNoiseToast) {
          hideLocalNetworkNoiseObject(object);
          if (typeof callback === "function") setTimeout(callback, 0);
          return null;
        }
        return originalRunAction.apply(this, arguments);
      };
      window.SAL_runAction.__officialProxyNetworkNoiseWrapped = true;
      patched = true;
    }

    if (patched) compatLog("official proxy network toast filter patch enabled");
    return patched;
  }

  function installDevFreeUnlockPatch() {
    if (!window.__officialProxyDevFreeUnlock) return false;
    var patched = false;

    if (window.commonPlayer) {
      commonPlayer.loginStatus = true;
      commonPlayer.userInfos = commonPlayer.userInfos || {};
      commonPlayer.userInfos.uid = commonPlayer.userInfos.uid || "local-player";
      commonPlayer.userInfos.code = commonPlayer.userInfos.code || "local-player";
      if (!/^\d+$/.test(String(commonPlayer.userInfos.gindex || ""))) {
        commonPlayer.userInfos.gindex = String(window.__officialProxyGameId || "1569947");
      }
      commonPlayer.userInfos.open_id = commonPlayer.userInfos.open_id || "";
      commonPlayer.userInfos.channel_type = commonPlayer.userInfos.channel_type || "";
      commonPlayer.userInfos.third_sign = commonPlayer.userInfos.third_sign || "";
      commonPlayer.login = commonPlayer.login || {};
      commonPlayer.login.midLogin = function (callback) {
        commonPlayer.loginStatus = true;
        if (typeof callback === "function") callback(true);
      };
    }
    patched = applyDevFlowerState() || patched;

    var scriptSrcDescriptor = Object.getOwnPropertyDescriptor(HTMLScriptElement.prototype, "src");
    if (scriptSrcDescriptor && scriptSrcDescriptor.set && !scriptSrcDescriptor.set.__officialProxyDevFreeUnlockWrapped) {
      Object.defineProperty(HTMLScriptElement.prototype, "src", {
        get: scriptSrcDescriptor.get,
        set: function (value) {
          var payload = getDevFreeUnlockPayload(value);
          var callbackName = payload && getJsonpCallbackName(value);
          if (payload && callbackName) {
            compatLog("official proxy platform unlock JSONP " + callbackName + " " + value);
            var script = callbackName + "(" + JSON.stringify(payload) + ");";
            return scriptSrcDescriptor.set.call(this, "data:text/javascript;charset=utf-8," + encodeURIComponent(script));
          }
          return scriptSrcDescriptor.set.call(this, value);
        }
      });
      Object.getOwnPropertyDescriptor(HTMLScriptElement.prototype, "src").set.__officialProxyDevFreeUnlockWrapped = true;
      compatLog("official proxy platform unlock JSONP patch enabled");
      patched = true;
    }

    if (window.OrgWeb && OrgWeb.prototype && !OrgWeb.prototype.__officialProxyDevFreeUnlockPatched) {
      OrgWeb.prototype.__officialProxyDevFreeUnlockPatched = true;
      OrgWeb.prototype.getIsUnLock = function () { return true; };
      patched = true;
    }

    return patched;
  }

  registerCompatPatch("platform unlock", 40, installDevFreeUnlockPatch);
  registerCompatPatch("local API", 50, installLocalRequestPatch);
  registerCompatPatch("network toast filter", 60, installNetworkNoiseToastFilterPatch);

  function installButtonPaddingPatch() {
    var forceEnabled = String(parseUrlParams(window.location.search).compatDButton || "") === "1";
    if (!forceEnabled && !hasCompatCapability("padded-dbutton")) return false;
    if (!window.org_data || !org_data.DButton || org_data.DButton.__officialProxyPadWrapped) return false;
    var OriginalDButton = org_data.DButton;
    var readI32LE = function (stream, pos) {
      try {
        return new DataView(stream.buffer).getInt32(pos, true);
      } catch (error) {
        return null;
      }
    };
    var PaddedDButton = function (stream) {
      if (stream && typeof stream.pos === "number" && stream.buffer && stream.pos + 5 < stream.buffer.byteLength) {
        var current = readI32LE(stream, stream.pos);
        var shifted = readI32LE(stream, stream.pos + 1);
        var head = new Uint8Array(stream.buffer, stream.pos, 1)[0];
        if (head === 0 && current % 256 === 0 && shifted > 0 && shifted < 10000) {
          stream.pos += 1;
        }
      }
      return new OriginalDButton(stream);
    };
    PaddedDButton.prototype = OriginalDButton.prototype;
    PaddedDButton.__officialProxyPadWrapped = true;
    org_data.DButton = PaddedDButton;
    compatLog("official proxy DButton padding compat enabled");
    return true;
  }

  function installNewDSystemPatch() {
    var forceEnabled = String(parseUrlParams(window.location.search).compatDSystem || "") === "1";
    var nativeV108CuiEnabled = hasCompatCapability("native-v108-sized-cui");
    if (!forceEnabled && !hasCompatCapability("extended-dsystem")) return false;
    if (!window.org_data || !org_data.DSystem || org_data.DSystem.__officialProxyNewPatched) return false;

    var parseEventList = function (stream) {
      var count = stream.getInt32();
      var events = new Array(count);
      for (var index = 0; index < count; index++) {
        stream.getInt32();
        events[index] = new org_data.DEvent(stream);
      }
      return events;
    };

    var NewCustomUIItem = function (stream) {
      stream.getInt32();
      this.event = parseEventList(stream);
      this.type = stream.getInt32();
      this.isUserString = stream.getInt32() !== 0;
      this.image1 = stream.readStringE();
      this.image2 = stream.readStringE();
      this.stringIndex = stream.getInt32();
      this.isUserVar = stream.getInt32() !== 0;
      this.x = stream.getInt32();
      this.y = stream.getInt32();
      this.isUserIndex = stream.getInt32() !== 0;
      this.index = stream.getInt32();
      this.maxIndex = stream.getInt32();
      this.color = new org_data.OColor(stream.readStringE());
    };

    var NewCustomUIData = function (stream, declaredSize) {
      var start = stream.pos;
      stream.getInt32();
      this.loadEvent = parseEventList(stream);
      this.afterEvent = [];
      var controlCount = stream.getInt32();
      this.controls = new Array(controlCount);
      for (var index = 0; index < controlCount; index++) {
        this.controls[index] = new NewCustomUIItem(stream);
      }
      this.showEffect = stream.getInt32();
      this.isMouseExit = stream.getInt32() !== 0;
      this.isKeyExit = stream.getInt32() !== 0;
      var actualSize = stream.pos - start;
      if (declaredSize !== actualSize) {
        throw new Error("new CUI size mismatch declared=" + declaredSize + " actual=" + actualSize + " start=" + start);
      }
    };

    var NewDSystem = function (stream) {
      this.Cuis = null;
      this.FontStyleColor = "";
      this.FontStroke = false;
      this.FontFilter = false;
      stream.getInt32();
      this.FontName = stream.readStringE();
      this.FontSize = stream.getInt32();
      this.FontSize *= 0.8;
      this.FontTalkColor = new org_data.OColor(stream.readStringE());
      this.FontUiColor = new org_data.OColor(stream.readStringE());
      if (GloableData.getInstance().gameInfo.ver >= 101) this.FontStyle = stream.getInt32();
      if (this.FontStyle !== 0) {
        switch (this.FontStyle) {
          case 1: this.FontFilter = true; this.FontStyleColor = "#000000"; break;
          case 2: this.FontFilter = true; this.FontStyleColor = "#999b9f"; break;
          case 3: this.FontFilter = true; this.FontStyleColor = "#FFFFFF"; break;
          case 4: this.FontStroke = true; this.FontStyleColor = "#000000"; break;
          case 5: this.FontStroke = true; this.FontStyleColor = "#999b9f"; break;
          case 6: this.FontStroke = true; this.FontStyleColor = "#FFFFFF"; break;
        }
      }
      this.SkipTitle = stream.getInt32() !== 0;
      this.StartStoryId = stream.getInt32();
      stream.getInt32();
      this.IconName = new org_data.DFileName(stream);
      this.ShowAD = stream.getInt32() !== 0;
      this.AuthorWords = stream.readStringE();
      this.AuthorWordsTiming = stream.getInt32();
      this.AutoRun = stream.getInt32() !== 0;
      this.ShowSystemMenu = stream.getInt32() !== 0;
      this.SEClick = new org_data.DMusicItem(stream);
      this.SEMove = new org_data.DMusicItem(stream);
      this.SECancel = new org_data.DMusicItem(stream);
      this.SEError = new org_data.DMusicItem(stream);
      this.Title = new org_data.DTitle(stream);
      this.GameMenu = new org_data.DGameMenu(stream);
      this.CG = new org_data.DCG(stream);
      this.BGM = new org_data.DBGM(stream);
      this.SaveData = new org_data.DSaveData(stream);
      this.MessageBox = new org_data.DMessageBox(stream);
      this.Replay = new org_data.DReplay(stream);
      this.Setting = new org_data.DSetting(stream);

      var oldButtonCount = stream.getInt32();
      var buttonTableHeader = null;
      var buttonCount = oldButtonCount;
      if (oldButtonCount === 80 && stream.pos + 12 <= stream.buffer.byteLength) {
        var headerMarker1 = stream.getInt32();
        var headerMarker2 = stream.getInt32();
        var declaredButtonCount = stream.getInt32();
        if (headerMarker1 === 80 && headerMarker2 === 80 && declaredButtonCount > oldButtonCount && declaredButtonCount < 10000) {
          buttonTableHeader = [oldButtonCount, headerMarker1, headerMarker2, declaredButtonCount];
          buttonCount = declaredButtonCount;
        } else {
          stream.pos -= 12;
        }
      }
      this.Buttons = new Array(buttonCount);
      for (var index = 0; index < buttonCount; index++) {
        this.Buttons[index] = new org_data.DButton(stream);
      }

      this.UIInitSave = stream.getInt32() !== 0;
      this.Cuis = null;
      this.MenuIndex = 0;
      GloableData.getInstance().autoPlay = this.AutoRun;
      if (GloableData.getInstance().gameInfo.ver >= 103) {
        var cuiCount = stream.getInt32();
        this.Cuis = new Array(cuiCount);
        for (var cuiIndex = 0; cuiIndex < cuiCount; cuiIndex++) {
          var declaredSize;
          var cuiStart;
          try {
            if (nativeV108CuiEnabled) {
              cuiStart = stream.pos;
              declaredSize = new DataView(stream.buffer).getInt32(cuiStart, true);
              this.Cuis[cuiIndex] = new org_data.DCustomUIData(stream);
              var actualSize = stream.pos - cuiStart - 4;
              if (declaredSize !== actualSize) {
                throw new Error("native v108 CUI size mismatch declared=" + declaredSize +
                  " actual=" + actualSize + " start=" + cuiStart);
              }
            } else {
              declaredSize = stream.getInt32();
              cuiStart = stream.pos;
              this.Cuis[cuiIndex] = new NewCustomUIData(stream, declaredSize);
            }
          } catch (error) {
            if (nativeV108CuiEnabled) {
              compatLog("official proxy native v108 CUI failed index=" + cuiIndex +
                " declared=" + declaredSize + " start=" + cuiStart +
                " pos=" + stream.pos + " error=" +
                (error && (error.stack || error.message) || error));
            }
            throw error;
          }
        }
        this.MenuIndex = stream.getInt32();
      }
      compatLog("official proxy DSystem compat parsed buttons=" + buttonCount + " header=" + (buttonTableHeader ? buttonTableHeader.join("/") : oldButtonCount) + " pos=" + stream.pos);
    };
    NewDSystem.__officialProxyNewPatched = true;
    org_data.DSystem = NewDSystem;
    compatLog("official proxy DSystem/CUI compat enabled");
    return true;
  }

  registerCompatPatch("DButton padding", 10, installButtonPaddingPatch);
  registerCompatPatch("DSystem/CUI", 20, installNewDSystemPatch);

  function installJumpStoryV2063Patch() {
    if (!hasCompatCapability("jump-story-v2063")) return false;
    if (typeof MainEventLine === "undefined" || !MainEventLine.prototype) return false;
    if (MainEventLine.prototype.__officialProxyJumpStoryV2063Wrapped) return false;

    var originalMakeEvent = MainEventLine.prototype.makeEvent;
    MainEventLine.prototype.makeEvent = function (event) {
      var currentEvent = event || (this.story && this.story.events && this.story.events[this.pos]);
      if (currentEvent && currentEvent.Code === 2063) {
        currentEvent.Code = 206;
        compatLog("official proxy v2063 jump-story compat story=" + currentEvent.Argv[0]);
      }
      return originalMakeEvent.apply(this, arguments);
    };
    MainEventLine.prototype.__officialProxyJumpStoryV2063Wrapped = true;
    compatLog("official proxy v2063 jump-story compat enabled");
    return true;
  }

  registerCompatPatch("v2063 jump-story", 30, installJumpStoryV2063Patch);

  function installFreeTimeBypass() {
    var patched = false;
    var bypass = function (success, failure) {
      this.__officialProxyFreeTimeBypassed = true;
      if (window.GloableData && GloableData.getInstance) {
        GloableData.getInstance().isFreeLimit = false;
        GloableData.getInstance().isFreeTime = 0;
      }
      compatLog("official proxy bypass free-time gate");
      if (typeof success === "function") return success();
      if (typeof failure === "function") return failure();
      return undefined;
    };

    if (window.OrgWebFree && OrgWebFree.prototype && !OrgWebFree.prototype.__officialProxyFreeTimeBypassed) {
      OrgWebFree.prototype.getFreeTime = bypass;
      OrgWebFree.prototype.__officialProxyFreeTimeBypassed = true;
      patched = true;
    }

    if (window.UIManager && UIManager.getInstance) {
      var ui;
      try {
        ui = UIManager.getInstance();
      } catch (error) {
        return patched;
      }
      var layer = ui && ui.orgWebFreeLayer;
      if (layer && !layer.__officialProxyFreeTimeBypassed) {
        layer.getFreeTime = bypass;
        layer.__officialProxyFreeTimeBypassed = true;
        patched = true;
      }
    }

    if (patched) compatLog("official proxy local free-time gate bypass enabled");
    return patched;
  }

  registerCompatPatch("free-time", 100, installFreeTimeBypass);

  function installStorageTracePatch() {
    if (window.__officialProxyStorageTracePatched) return false;
    var hasStorageAPI =
      typeof window.SAL_setStorage === "function" ||
      typeof window.SAL_getStorage === "function" ||
      typeof window.SAL_removeStorage === "function" ||
      typeof window.SAL_getStorageInfo === "function" ||
      (window.OStorage && OStorage.prototype);
    if (!hasStorageAPI) return false;

    window.__officialProxyStorageTracePatched = true;
    window.__officialProxyStorageTrace = window.__officialProxyStorageTrace || [];

    var AUTO_SAVE_SUFFIX = "-100";
    var PRIMARY_ARCHIVE_SLOT = "1";
    var COMPAT_ARCHIVE_SLOT = "0";
    var SAVE_INDEX_SUFFIX = "SaveFileIndex";
    var SAVE_INDEX_LOCAL_SUFFIX = "SaveFileIndexLocal";
    var SAVE_ICON_SUFFIX = "icon";
    var BRIDGE_MARKER_SUFFIX = "__officialProxyAutoArchiveBridge";
    var bridgeWriteDepth = 0;

    function trace(action, key, value) {
      var item = {
        action: action,
        key: key === undefined ? "" : String(key),
        length: value === undefined || value === null ? 0 : String(value).length,
        at: Date.now()
      };
      window.__officialProxyStorageTrace.push(item);
      if (window.__officialProxyStorageTrace.length > 100) window.__officialProxyStorageTrace.shift();
      compatLog("official proxy storage " + action + " key=" + item.key + " len=" + item.length);
    }

    function isMissingStorageValue(value) {
      return value === undefined || value === null || value === "";
    }

    function readRaw(storage, originalLoadFile, key) {
      try {
        return originalLoadFile.call(storage, key);
      } catch (error) {
        return null;
      }
    }

    function writeRaw(storage, originalSaveFile, key, value) {
      try {
        bridgeWriteDepth += 1;
        originalSaveFile.call(storage, key, value);
        return true;
      } catch (error) {
        return false;
      } finally {
        bridgeWriteDepth -= 1;
      }
    }

    function archivePrefixFromKey(key) {
      key = String(key || "");
      if (key.indexOf("local-player") < 0) return "";
      if (key.slice(-SAVE_INDEX_LOCAL_SUFFIX.length) === SAVE_INDEX_LOCAL_SUFFIX) {
        return key.slice(0, -SAVE_INDEX_LOCAL_SUFFIX.length);
      }
      if (key.slice(-SAVE_INDEX_SUFFIX.length) === SAVE_INDEX_SUFFIX) {
        return key.slice(0, -SAVE_INDEX_SUFFIX.length);
      }
      if (key.slice(-SAVE_ICON_SUFFIX.length) === SAVE_ICON_SUFFIX) {
        return key.slice(0, -SAVE_ICON_SUFFIX.length);
      }
      return "";
    }

    function archivePrefixFromAutoKey(key) {
      key = String(key || "");
      if (key.indexOf("local-player") < 0) return "";
      return key.slice(-AUTO_SAVE_SUFFIX.length) === AUTO_SAVE_SUFFIX ? key.slice(0, -AUTO_SAVE_SUFFIX.length) : "";
    }

    function isManualArchiveSlotKey(key) {
      key = String(key || "");
      return /local-player\d+$/.test(key);
    }

    function archivePrefixFromManualSlotKey(key) {
      var match = String(key || "").match(/^(.*local-player)\d+$/);
      return match ? match[1] : "";
    }

    function buildArchiveIconValue(autoSaveValue) {
      var picurl = "";
      try {
        var parsed = JSON.parse(autoSaveValue);
        var thumb = parsed && parsed.Thumbnail;
        picurl = thumb && (thumb.base64 || thumb.picurl || thumb.cloudImageUrl || thumb.cloudImageUr || "") || "";
      } catch (error) {}
      if (!picurl) picurl = buildArchivePlaceholderImage();

      var slots = [];
      for (var index = 0; index < 20; index++) {
        var active = index === parseInt(PRIMARY_ARCHIVE_SLOT, 10);
        slots.push({
          index: index,
          picurl: active ? picurl : "",
          name: active ? "自动存档" : "",
          date: active ? Date.now() : -1
        });
      }
      return encodeURIComponent(JSON.stringify(slots));
    }

    function buildArchivePlaceholderImage() {
      try {
        var canvas = document.createElement("canvas");
        canvas.width = 240;
        canvas.height = 135;
        var ctx = canvas.getContext("2d");
        var gradient = ctx.createLinearGradient(0, 0, canvas.width, canvas.height);
        gradient.addColorStop(0, "#f9e8ff");
        gradient.addColorStop(1, "#b59cff");
        ctx.fillStyle = gradient;
        ctx.fillRect(0, 0, canvas.width, canvas.height);
        ctx.fillStyle = "rgba(255,255,255,.75)";
        ctx.fillRect(12, 12, canvas.width - 24, canvas.height - 24);
        ctx.strokeStyle = "rgba(134,94,190,.55)";
        ctx.lineWidth = 3;
        ctx.strokeRect(18, 18, canvas.width - 36, canvas.height - 36);
        ctx.fillStyle = "#7b56b3";
        ctx.font = "bold 22px sans-serif";
        ctx.textAlign = "center";
        ctx.textBaseline = "middle";
        ctx.fillText("AUTO SAVE", canvas.width / 2, canvas.height / 2);
        return canvas.toDataURL("image/png");
      } catch (error) {
        return "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/p9sAAAAASUVORK5CYII=";
      }
    }

    function ensureAutoArchiveBridge(storage, originalLoadFile, originalSaveFile, prefix, reason) {
      if (!prefix) return false;
      var autoKey = prefix + AUTO_SAVE_SUFFIX;
      var autoSaveValue = readRaw(storage, originalLoadFile, autoKey);
      if (isMissingStorageValue(autoSaveValue)) return false;

      var markerKey = prefix + BRIDGE_MARKER_SUFFIX;
      var marker = readRaw(storage, originalLoadFile, markerKey);
      if (marker === "manual") return false;

      var slotKey = prefix + PRIMARY_ARCHIVE_SLOT;
      var compatSlotKey = prefix + COMPAT_ARCHIVE_SLOT;
      var indexKey = prefix + SAVE_INDEX_SUFFIX;
      var localIndexKey = prefix + SAVE_INDEX_LOCAL_SUFFIX;
      var iconKey = prefix + SAVE_ICON_SUFFIX;
      var changed = false;

      if (isMissingStorageValue(readRaw(storage, originalLoadFile, slotKey)) || marker === "auto") {
        changed = writeRaw(storage, originalSaveFile, slotKey, autoSaveValue) || changed;
      }
      if (isMissingStorageValue(readRaw(storage, originalLoadFile, compatSlotKey)) || marker === "auto") {
        changed = writeRaw(storage, originalSaveFile, compatSlotKey, autoSaveValue) || changed;
      }
      if (isMissingStorageValue(readRaw(storage, originalLoadFile, indexKey)) || marker === "auto") {
        changed = writeRaw(storage, originalSaveFile, indexKey, "0||" + PRIMARY_ARCHIVE_SLOT) || changed;
      }
      if (isMissingStorageValue(readRaw(storage, originalLoadFile, localIndexKey)) || marker === "auto") {
        changed = writeRaw(storage, originalSaveFile, localIndexKey, PRIMARY_ARCHIVE_SLOT) || changed;
      }
      if (isMissingStorageValue(readRaw(storage, originalLoadFile, iconKey)) || marker === "auto") {
        changed = writeRaw(storage, originalSaveFile, iconKey, buildArchiveIconValue(autoSaveValue)) || changed;
      }
      if (marker !== "auto") {
        changed = writeRaw(storage, originalSaveFile, markerKey, "auto") || changed;
      }
      if (changed) compatLog("official proxy storage bridged autosave archive prefix=" + prefix + " reason=" + reason);
      return changed;
    }

    function bridgeKnownAutoArchives(storage, originalLoadFile, originalSaveFile, originalGetAllFileName) {
      var keys;
      try {
        keys = originalGetAllFileName.call(storage) || [];
      } catch (error) {
        return false;
      }
      var changed = false;
      for (var index = 0; index < keys.length; index++) {
        changed = ensureAutoArchiveBridge(storage, originalLoadFile, originalSaveFile, archivePrefixFromAutoKey(keys[index]), "scan") || changed;
      }
      return changed;
    }

    if (typeof window.SAL_setStorage === "function" && !window.SAL_setStorage.__officialProxyWrapped) {
      var originalSetStorage = window.SAL_setStorage;
      window.SAL_setStorage = function (key, value, callback) {
        trace("SAL_setStorage", key, value);
        return originalSetStorage.apply(this, arguments);
      };
      window.SAL_setStorage.__officialProxyWrapped = true;
    }

    if (typeof window.SAL_getStorage === "function" && !window.SAL_getStorage.__officialProxyWrapped) {
      var originalGetStorage = window.SAL_getStorage;
      window.SAL_getStorage = function (key, callback) {
        trace("SAL_getStorage", key);
        return originalGetStorage.call(this, key, function (value) {
          trace("SAL_getStorageResult", key, value);
          if (typeof callback === "function") callback(value);
        });
      };
      window.SAL_getStorage.__officialProxyWrapped = true;
    }

    if (typeof window.SAL_removeStorage === "function" && !window.SAL_removeStorage.__officialProxyWrapped) {
      var originalRemoveStorage = window.SAL_removeStorage;
      window.SAL_removeStorage = function (key, callback) {
        trace("SAL_removeStorage", key);
        return originalRemoveStorage.apply(this, arguments);
      };
      window.SAL_removeStorage.__officialProxyWrapped = true;
    }

    if (typeof window.SAL_getStorageInfo === "function" && !window.SAL_getStorageInfo.__officialProxyWrapped) {
      var originalGetStorageInfo = window.SAL_getStorageInfo;
      window.SAL_getStorageInfo = function (callback) {
        trace("SAL_getStorageInfo", "*");
        return originalGetStorageInfo.call(this, function (keys) {
          trace("SAL_getStorageInfoResult", "*", JSON.stringify(keys || []));
          if (typeof callback === "function") callback(keys);
        });
      };
      window.SAL_getStorageInfo.__officialProxyWrapped = true;
    }

    if (window.OStorage && OStorage.prototype && !OStorage.prototype.__officialProxyWrapped) {
      OStorage.prototype.__officialProxyWrapped = true;
      var originalSaveFile = OStorage.prototype.saveFile;
      var originalLoadFile = OStorage.prototype.loadFile;
      var originalRemoveFile = OStorage.prototype.removeFile;
      var originalGetAllFileName = OStorage.prototype.getAllFileName;
      OStorage.prototype.saveFile = function (key, value) {
        trace("OStorage.saveFile", key, value);
        var result = originalSaveFile.apply(this, arguments);
        if (!bridgeWriteDepth && isManualArchiveSlotKey(key)) {
          writeRaw(this, originalSaveFile, archivePrefixFromManualSlotKey(key) + BRIDGE_MARKER_SUFFIX, "manual");
        }
        ensureAutoArchiveBridge(this, originalLoadFile, originalSaveFile, archivePrefixFromAutoKey(key), "autosave");
        return result;
      };
      OStorage.prototype.loadFile = function (key) {
        var value = originalLoadFile.apply(this, arguments);
        if (isMissingStorageValue(value)) {
          ensureAutoArchiveBridge(this, originalLoadFile, originalSaveFile, archivePrefixFromKey(key), "load");
          value = originalLoadFile.apply(this, arguments);
        }
        trace("OStorage.loadFile", key, value);
        return value;
      };
      OStorage.prototype.removeFile = function (key) {
        trace("OStorage.removeFile", key);
        return originalRemoveFile.apply(this, arguments);
      };
      OStorage.prototype.getAllFileName = function () {
        bridgeKnownAutoArchives(this, originalLoadFile, originalSaveFile, originalGetAllFileName);
        var keys = originalGetAllFileName.apply(this, arguments);
        trace("OStorage.getAllFileName", "*", JSON.stringify(keys || []));
        return keys;
      };
    }

    compatLog("official proxy storage trace patch enabled");
    return true;
  }

  registerCompatPatch("storage trace", 110, installStorageTracePatch);

  function install() {
    return installRegisteredCompatPatches();
  }

  install();
  var tries = 0;
  var timer = setInterval(function () {
    tries += 1;
    install();
    if (tries >= 120) clearInterval(timer);
  }, 100);
})();
