[CmdletBinding()]
param(
    [switch]$Check
)

$ErrorActionPreference = "Stop"
$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
$sourceRoot = Join-Path $repoRoot "official_player_compat_src"
$outputPath = Join-Path $repoRoot "official_player_compat.js"
$sourceFiles = @(
    "00-core.js",
    "05-game-profiles.js",
    "10-built-in-menu.js",
    "20-platform-state.js",
    "30-local-save.js",
    "40-platform-api.js",
    "50-binary-parser.js",
    "60-free-time.js",
    "70-storage-trace.js",
    "90-bootstrap.js"
)

$parts = foreach ($sourceFile in $sourceFiles) {
    $path = Join-Path $sourceRoot $sourceFile
    if (-not (Test-Path $path)) {
        throw "Missing compatibility source module: $path"
    }
    ((Get-Content -Raw -Encoding UTF8 $path) -replace "`r`n?", "`n").TrimEnd()
}

$content = @(
    "// Generated by scripts/build-official-player-compat.ps1. Edit official_player_compat_src instead."
    "(function () {"
    ($parts -join "`n`n")
    "})();"
    ""
) -join "`n"

if ($Check) {
    if (-not (Test-Path $outputPath)) {
        throw "Generated compatibility bundle is missing: $outputPath"
    }
    $existing = (Get-Content -Raw -Encoding UTF8 $outputPath) -replace "`r`n?", "`n"
    if ($existing -cne $content) {
        throw "official_player_compat.js is stale. Run .\scripts\build-official-player-compat.ps1"
    }
    Write-Host "official_player_compat.js is up to date"
    exit 0
}

[IO.File]::WriteAllText($outputPath, $content, [Text.UTF8Encoding]::new($false))
Write-Host "Generated: $outputPath"
